spring.application.name=project07_oneToMany


spring.datasource.url=jdbc:mysql://localhost:3306/oneTOmanyStudents


spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true