server.port=8888

# Activate JDBC (DB-based config)
spring.profiles.active=jdbc

# DB connection
spring.datasource.url=jdbc:mysql://localhost:3306/config_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# IMPORTANT: Proper SQL (single line in properties)
spring.cloud.config.server.jdbc.sql=SELECT property_key, property_value FROM configuration WHERE application=? AND profile=? AND label=?

# (optional but useful)
spring.application.name=config-server
management.endpoints.web.exposure.include=*