# Admin Server Port
server.port=9091

# App Name
spring.application.name=ADMIN-SERVER


# Connect to YOUR Eureka Server (PORT 8084)
eureka.client.service-url.defaultZone=http://localhost:8084/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Actuator (VERY IMPORTANT)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.boot.admin.discovery.ignored-services=ADMIN-SERVER