spring.application.name=serviceGateway

server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8084/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webmvc.routes[0].id=serviceAdmin
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://SERVICEADMIN
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=path=/admin/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=serviceHospital
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://SERVICEHOSPITAL
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=path=/hospital/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=serviceDonor
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://SERVICEDONOR
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=path=/donor/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[3].id=serviceAuth
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://SERVICEAUTH
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=path=/auth/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1

server.servlet.context-path=/gateway