spring.application.name=project18_excelwork

spring.datasource.url=jdbc:mysql://localhost:3306/pr18excelwork


spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-request-size=1MB
spring.servlet.multipart.max-file-size=1MB